INSERT INTO gifts (name, emoji, description, price_stars, rarity, is_limited, total_supply) VALUES ('Красная роза', '🌹', 'Символ любви и уважения', 50, 'common', FALSE, NULL) ON CONFLICT DO NOTHING;
INSERT INTO gifts (name, emoji, description, price_stars, rarity, is_limited, total_supply) VALUES ('Торт', '🎂', 'С Днём рождения!', 100, 'common', FALSE, NULL) ON CONFLICT DO NOTHING;
INSERT INTO gifts (name, emoji, description, price_stars, rarity, is_limited, total_supply) VALUES ('Бриллиант', '💎', 'Редкий и ценный подарок', 500, 'rare', FALSE, NULL) ON CONFLICT DO NOTHING;
INSERT INTO gifts (name, emoji, description, price_stars, rarity, is_limited, total_supply) VALUES ('Ракета', '🚀', 'Для настоящих первопроходцев', 250, 'rare', FALSE, NULL) ON CONFLICT DO NOTHING;
INSERT INTO gifts (name, emoji, description, price_stars, rarity, is_limited, total_supply) VALUES ('Корона', '👑', 'Для королей и королев', 1000, 'epic', TRUE, 5000) ON CONFLICT DO NOTHING;
INSERT INTO gifts (name, emoji, description, price_stars, rarity, is_limited, total_supply) VALUES ('Звезда', '⭐', 'Подари звезду другу', 25, 'common', FALSE, NULL) ON CONFLICT DO NOTHING;
INSERT INTO gifts (name, emoji, description, price_stars, rarity, is_limited, total_supply) VALUES ('Огонь', '🔥', 'Горячий подарок', 75, 'common', FALSE, NULL) ON CONFLICT DO NOTHING;
INSERT INTO gifts (name, emoji, description, price_stars, rarity, is_limited, total_supply) VALUES ('Единорог', '🦄', 'Легендарный подарок', 2500, 'legendary', TRUE, 1000) ON CONFLICT DO NOTHING;
INSERT INTO gifts (name, emoji, description, price_stars, rarity, is_limited, total_supply) VALUES ('Шампанское', '🥂', 'Отпразднуй вместе!', 150, 'rare', FALSE, NULL) ON CONFLICT DO NOTHING;
INSERT INTO gifts (name, emoji, description, price_stars, rarity, is_limited, total_supply) VALUES ('Плюшевый мишка', '🧸', 'Милый и уютный', 80, 'common', FALSE, NULL) ON CONFLICT DO NOTHING;
INSERT INTO premium_plans (name, duration_months, price_stars, price_rub, features) VALUES ('MRAX Premium', 1, 500, 299, '["Без рекламы","Уникальные стикеры","Голосовые HD","Файлы до 4 ГБ","Бейдж Premium","Анимированный аватар","Невидимый режим+","Облако 100 ГБ"]') ON CONFLICT DO NOTHING;
INSERT INTO premium_plans (name, duration_months, price_stars, price_rub, features) VALUES ('MRAX Premium', 3, 1300, 799, '["Без рекламы","Уникальные стикеры","Голосовые HD","Файлы до 4 ГБ","Бейдж Premium","Анимированный аватар","Невидимый режим+","Облако 100 ГБ","Приоритетная поддержка"]') ON CONFLICT DO NOTHING;
INSERT INTO premium_plans (name, duration_months, price_stars, price_rub, features) VALUES ('MRAX Premium', 12, 4500, 2499, '["Без рекламы","Уникальные стикеры","Голосовые HD","Файлы до 4 ГБ","Бейдж Premium","Анимированный аватар","Невидимый режим+","Облако 200 ГБ","Приоритетная поддержка","Эксклюзивные подарки"]') ON CONFLICT DO NOTHING